# -*- coding: utf-8 -*-
from . import apirest
from . import lista_cargamentos
from . import lista_productos
from . import lista_ventas
from . import lista_compras
from . import lista_clientes
from . import lista_empleados
from . import lista_proveedores
from . import lista_reparacion
from . import lista_productos_delete
from . import lista_facturas_cliente
from . import lista_clientes_delete
from . import lista_empleados_delete
from . import lista_proveedores_delete
from . import lista_compras_delete
from . import addProducto
from . import lista_reparacion_delete
from . import lista_ventacompleta_delete